# docker-compose up -d --build
# docker run -i -t -p "80:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql mattrayner/lamp:latest

version: "2"
services:
  node:
    #image: "node:10"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-budget-api
    user: "node"
    working_dir: /home/olle/budget-api
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=nginx.ropaolle.se
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=nginx.ropaolle.se
      - LETSENCRYPT_EMAIL=ropaolle@gmail.com
    volumes:
      - ./:/home/olle/budget-api
    ports:
      - "3001:3001"
    #command: "npm start"


#docker run --detach \
#    --name grafana \
#    --env "VIRTUAL_HOST=nginx.ropaolle.se" \
#    --env "VIRTUAL_PORT=3000" \
#    --env "LETSENCRYPT_HOST=nginx.ropaolle.se" \
#    --env "LETSENCRYPT_EMAIL=ropaolle@gmail.com" \
#    grafana/grafana

#80: 192.168.10.2/121
#443: 192.168.10.107/121